RDTH/Controllers/FaqController.cs
using Microsoft.AspNetCore.Mvc;
using RDTH.Data;
using RDTH.Models.FaqViewModel;
using System.Linq;

namespace RDTH.Controllers
{
    public class FaqController : Controller
    {
        private IFaq _faqService;
        public FaqController(IFaq faqService)
        {
            _faqService = faqService;
        }

        public IActionResult Index()
        {
            var faq = _faqService.GetAll().Select(f => new FaqDetailModel
            {
                Id = f.Id,
                Question = f.Question,
                Answer = f.Answer
            });

            FaqIndexModel model = new FaqIndexModel()
            {
               Faqs=faq
            };

            return View(model);
        }
    }
}

RDTH/Controllers/ModController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RDTH.Data;
using RDTH.Data.Models;
using RDTH.Models;
using RDTH.Models.ModViewModel;
using System.Linq;

namespace RDTH.Controllers
{
    [Authorize(Roles = "User")]
    public class ModController : Controller
    {
        private readonly IStatusService _statusService;
        private readonly IMod _modservice;
        private readonly ICustomer _cusService;
        private readonly UserManager<ApplicationUser> _userManager;

        public ModController(IStatusService statusService,
            IMod modService,
            ICustomer CusService,
            UserManager<ApplicationUser> userManager)
        {
            _statusService = statusService;
            _modservice = modService;
            _userManager = userManager;
            _cusService = CusService;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(ModAddModel model)
        {
            if (ModelState.IsValid)
            {
                MovieOnDemand movie = new MovieOnDemand
                {
                    Movie = model.Movie,
                    MovieTime = model.MovieTime,
                    Status = _statusService.GetByName("Pending"),
                    Customer = _cusService.GetByUser(_userManager.GetUserId(HttpContext.User))
                };
                _modservice.Add(movie);

                ViewBag.success = "success";
                ViewBag.msg = "Your Request Has been send to Admin, Thank You";

                ModelState.Clear();
                return View();
            }
            return View(model);
        }

        public IActionResult RequestHistory()
        {
            var user = _userManager.GetUserId(HttpContext.User);
            var customer = _cusService.GetByUser(user);
            var Mod = _modservice.GetByCustomer(customer.Id).
                Select(m => new ModDetailModel
                {
                   Movie=m.Movie,
                   MovieTime=m.MovieTime,
                   Status=m.Status.Name
                });

            var model = new ModIndexModel
            {
                ModList = Mod
            };

            return View(model);
        }
    }
}

RDTH/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RDTH.Data;
using RDTH.Models;

namespace RDTH.Controllers
{
    public class OrderController : Controller
    {
        private readonly IDealerService _dealerService;
        private readonly IDistributerService _disService;
        UserManager<ApplicationUser> _userManager;

        public OrderController(
            IOrder orderService,
            IDealerService dealerService,
            IDistributerService disService,
            UserManager<ApplicationUser> userManager)
        {
            _dealerService = dealerService;
            _disService = disService;
            _userManager = userManager;

        }

        [Authorize(Roles = "Dealer")]
        public IActionResult DealerOrder()
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            var dealer = _dealerService.GetByUserId(userId);
            var model = _dealerService.GetOrders(dealer.Id);
            return View(model);
        }

        [Authorize(Roles = "Distributer")]
        public IActionResult DistributerOrder()
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            var distributer = _disService.GetByUserId(userId);
            var model = _disService.GetOrders(distributer.Id);
            return View(model);
        }
    }
}

RDTH/Controllers/SetboxController.cs
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RDTH.Data;
using RDTH.Data.Models;
using RDTH.Models;
using RDTH.Models.SetBoxViewModel;

namespace RDTH.Controllers
{
    public class SetboxController : Controller
    {
        private readonly ISetBoxService _SetBoxService;
        private readonly INewSetBoxRequest _setBoxRequest;
        private readonly ICardService _cardService;
        private readonly IStatusService _statusService;
        private readonly UserManager<ApplicationUser> _userManager;


        public SetboxController(
            ISetBoxService setboxService,
            INewSetBoxRequest setBoxRequest,
            ICardService cardService,
            IStatusService statusService,
            UserManager<ApplicationUser> userManager
            )
        {
            _SetBoxService = setboxService;
            _setBoxRequest = setBoxRequest;
            _statusService = statusService;
            _cardService = cardService;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var devices = _SetBoxService.GetAll().Select(s => new SetBoxDetailModel()
            {
                Id = s.Id,
                ImageUrl = s.ImageUrl,
                Name = s.Name,
                Price = s.Price,
                Specification = s.Specification
            });

            if (TempData["OrderPlaced"]!=null)
            {
                ViewBag.OrderPlaced = TempData["OrderPlaced"].ToString();
                ViewBag.OrderMsg = TempData["OrderMsg"].ToString();
            }

            if (TempData["SetBoxChanged"] != null)
            {
                ViewBag.SetBoxChange=TempData["SetBoxChanged"].ToString();
                ViewBag.SetBoxChangeMsg=TempData["SetBoxChangedMsg"].ToString();
            }


            var model = new SetBoxIndexModel() { SetBoxList = devices };
            return View(model);
        }

        public IActionResult Detail(int id)
        {
            var setBox = _SetBoxService.GetById(id);
            var model = new SetBoxDetailModel()
            {
                Id = setBox.Id,
                ImageUrl = setBox.ImageUrl,
                Name = setBox.Name,
                Price = setBox.Price,
                Specification = setBox.Specification
            };

            return View(model);
        }

        [Authorize(Roles = "User")]
        [HttpGet]
        public IActionResult ChangeSetBox(int? setBoxId)
        {
            if (setBoxId == null)
            {
                return NotFound();
            }
            var setBox = _SetBoxService.GetById(setBoxId);

            if (setBox == null)
            {
                return NotFound();
            }

            var model = new SetBoxDetailModel
            {
                Id = setBox.Id,
                Name = setBox.Name
            };
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "User")]
        public IActionResult ChangeSetBox(SetBoxDetailModel model)
        {
            var card = _cardService.GetCurrentUserCard(_userManager.GetUserId(HttpContext.User));

            if (card == null)
            {
                return NotFound();
            }
            if (_setBoxRequest.CheckAlreadyApplied(card.CardNumber))
            {
                return View("AlreadyApplied");
            }

            if (ModelState.IsValid)
            {
                var request = new NewSetBoxRequest()
                {
                    Setbox = _SetBoxService.GetById(model.Id),
                    Card = card,
                    Status = _statusService.GetByName("Pending")
                };

                _setBoxRequest.Add(request);
                TempData["SetBoxChanged"] = "success";
                TempData["SetBoxChangedMsg"] = "Your Request has been sent.";
                ModelState.Clear();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [Authorize(Roles = "Distributer,Dealer")]
        public IActionResult CustomerSetBoxRequest()
        {
            Status st = _statusService.GetByName("AdminApproved");
            var model = _setBoxRequest.GetByStatus(st.Name);
            return View(model);
        }

        [Authorize(Roles = "Distributer,Dealer")]
        [HttpGet]
        public IActionResult Delivered(int? Id)
        {
            if (Id == null) {
                return NotFound();
            }
            var request = _setBoxRequest.GetById(Id);
            request.Status = _statusService.GetByName("Delivered");
            _setBoxRequest.Update(request);
            return RedirectToAction("CustomerSetBoxRequest");
        }
    }
}

RDTH/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - R-DTH (Satelite DishTv Service)</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-slate.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    @RenderSection("Styles", required: false)
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"><span style="font-family: 'Lato', sans-serif;"><i class="fa fa-television" aria-hidden="true"></i>  R-DTH</span></a>
            </div>
            <div class="navbar-collapse collapse">
                @await Html.PartialAsync("_NavMenu")
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <br />
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - RDTH Developed By Jawad Ahmed</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script src="https://use.fontawesome.com/b572303f9b.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

RDTH/Views/Shared/_NavMenu.cshtml
@using Microsoft.AspNetCore.Identity
@using RDTH.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    @if (User.IsInRole("User"))
    {
        <ul class="nav navbar-nav">
            <li><a asp-area="" asp-controller="Package" asp-action="MyPackage">MyPackage</a></li>
            <li><a asp-area="" asp-controller="Recharge" asp-action="">Recharge</a></li>
            <li><a asp-area="" asp-controller="Recharge" asp-action="History">Recharge History</a></li>
            <li><a asp-area="" asp-controller="Mod" asp-action="Index">Book Movie</a></li>
            <li><a asp-area="" asp-controller="Feedback" asp-action="">FeedBack</a></li>
            <li><a asp-area="" asp-controller="Faq" asp-action="Index">FAQ</a></li>
            <li><a asp-area="" asp-controller="CustomerCare" asp-action="">Locate Dealer</a></li>
        </ul>
    }
    @if (User.IsInRole("Distributer"))
    {
        <ul class="nav navbar-nav">
            <li><a asp-area="" asp-controller="Setbox" asp-action="Index">SetBox</a></li>
            <li><a asp-area="" asp-controller="Order" asp-action="DistributerOrder">My Orders</a></li>
            <li><a asp-area="" asp-controller="Payment" asp-action="DistributerPayment">My Payments</a></li>
            <li><a asp-area="" asp-controller="Faq" asp-action="Index">FAQ</a></li>
            <li>
                @await Component.InvokeAsync("CartTotalItems")
            </li>
        </ul>
    }
    @if (User.IsInRole("Dealer"))
    {
        <ul class="nav navbar-nav">
            <li><a asp-area="" asp-controller="Setbox" asp-action="Index">SetBox</a></li>
            <li><a asp-area="" asp-controller="Order" asp-action="DealerOrder">My Orders</a></li>
            <li><a asp-area="" asp-controller="Payment" asp-action="DealerPayment">My Payments</a></li>
            <li><a asp-area="" asp-controller="Faq" asp-action="Index">FAQ</a></li>
            <li><a asp-area="" asp-controller="CustomerCare" asp-action="Distributers">Distributers</a></li>
            <li><a asp-area="" asp-controller="SetBox" asp-action="CustomerSetBoxRequest">SetBox Requests</a></li>
            <li>
                @await Component.InvokeAsync("CartTotalItems")
            </li>
    </ul>
}
}
else
{
    <ul class="nav navbar-nav">
        <li><a asp-area="" asp-controller="Package" asp-action="Index">Packages</a></li>
        <li><a asp-area="" asp-controller="Setbox" asp-action="Index">SetBox</a></li>
        <li><a asp-area="" asp-controller="Recharge" asp-action="">Recharge</a></li>
        <li><a asp-area="" asp-controller="Feedback" asp-action="">FeedBack</a></li>
        <li><a asp-area="" asp-controller="Faq" asp-action="Index">FAQ</a></li>
        <li><a asp-area="" asp-controller="CustomerCare" asp-action="">Customer Care</a></li>
    </ul>
}