RDTH/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RDTH.Data;
using RDTH.Models;

namespace RDTH.Controllers
{
    public class OrderController : Controller
    {
        private readonly IDealerService _dealerService;
        private readonly IDistributerService _disService;
        UserManager<ApplicationUser> _userManager;

        public OrderController(
            IOrder orderService,
            IDealerService dealerService,
            IDistributerService disService,
            UserManager<ApplicationUser> userManager)
        {
            _dealerService = dealerService;
            _disService = disService;
            _userManager = userManager;

        }

        [Authorize(Roles = "Dealer")]
        public IActionResult DealerOrder()
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            var dealer = _dealerService.GetByUserId(userId);
            var model = _dealerService.GetOrders(dealer.Id);
            return View(model);
        }

        [Authorize(Roles = "Distributer")]
        public IActionResult DistributerOrder()
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            var distributer = _disService.GetByUserId(userId);
            var model = _disService.GetOrders(distributer.Id);
            return View(model);
        }
    }
}

RDTH/Controllers/PaymentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RDTH.Data;
using RDTH.Models;

namespace RDTH.Controllers
{
    public class PaymentController : Controller
    {
        private readonly IOrder _orderService;
        private readonly IDealerService _dealerService;
        private readonly IDistributerService _disService;
        UserManager<ApplicationUser> _userManager;

        public PaymentController(
            IOrder orderService,
            IDealerService dealerService,
            IDistributerService disService,
            UserManager<ApplicationUser> userManager)
        {
            _orderService = orderService;
            _dealerService = dealerService;
            _disService = disService;
            _userManager = userManager;

        }

        [Authorize(Roles = "Dealer")]
        public IActionResult DealerPayment()
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            var dealer = _dealerService.GetByUserId(userId);
            var model = _dealerService.GetPayments(dealer.Id);
            return View(model);
        }

        [Authorize(Roles = "Distributer")]
        public IActionResult DistributerPayment()
        {
            var userId = _userManager.GetUserId(HttpContext.User);
            var distributer = _disService.GetByUserId(userId);
            var model = _disService.GetPayments(distributer.Id);
            return View(model);
        }
    }
}

RDTH/Controllers/RechargeController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RDTH.Data;
using RDTH.Data.Models;
using RDTH.Models;
using RDTH.Models.RechargeViewModel;
using System;
using System.Linq;

namespace RDTH.Controllers
{
    public class RechargeController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IRechargeService _rechargeService;
        private readonly ICardService _cardService;
        private readonly IPackageService _packageService;
        private readonly ICustomerPackage _cpService;
        private readonly IStatusService _statusService;

        public RechargeController(
            IRechargeService rechargeService,
            IPackageService packageService,
            ICardService cardService,
            ICustomerPackage cpService,
            IStatusService statusService,
            UserManager<ApplicationUser> UserManager)
        {
            _userManager = UserManager;
            _rechargeService = rechargeService;
            _cardService = cardService;
            _packageService = packageService;
            _cpService = cpService;
            _statusService = statusService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(RechargeAddModel model)
        {
            DateTime now = DateTime.Now;

            if (model.CardExpiry < now)
            {
                ModelState.AddModelError("CardExpiry", "Your Credit Card is Expire");
                return View(model);
            }
            if (ModelState.IsValid)
            {
                var card = GetCard(model.Customercard);
                var package = GetPackage(card.Package.Id);

                Recharge recharge = new Recharge()
                {
                    CardExpiry = model.CardExpiry,
                    Cost = model.Total,
                    CreditCardNumber = model.CreditCardNumber,
                    CVV = model.CVV,
                    PaymentType = model.PaymentType,
                    RechargeDate = now,
                    CustomerCard = card,
                    Package = package
                };

                var cp = _cpService.GetByCardId(card.Id);
                cp.Status = _statusService.GetByName("Charged");
                cp.ExpirationDate = now.AddMonths(model.Months);
                cp.NumberOfMonths = model.Months;
                cp.Package = card.Package;
                cp.CustomerCard = card;

                _cpService.Update(cp);
                _rechargeService.Add(recharge);

                ModelState.Clear();
                ViewBag.success = "success";
                ViewBag.msg = "Your Account has been Recharge ,Thank You! for chossing our service";
                return View();

            }

            return View(model);
        }

        public IActionResult History()
        {
            CustomerCard card = _cardService.GetCurrentUserCard(_userManager.GetUserId(HttpContext.User));


            var rechargeHistory = _rechargeService.GetByCustomerCard(card.CardNumber).
                Select(r=>new RechargeHistoryDetailModel {
                    Charges=r.Package.Charges,
                    Customercard=r.CustomerCard.CardNumber,
                    Total=r.Cost,
                    OwnerName=r.CustomerCard.OwnerName,
                    PackageName=r.Package.PackageName,
                    PaymentType=r.PaymentType,
                    RechargeDate=r.RechargeDate
                });

            RechargeHistoryIndexModel model = new RechargeHistoryIndexModel {
                RechargeList = rechargeHistory
            };
            return View(model);
        }


        public JsonResult IsCardAvailable(string Customercard)
        {
            return Json(_cardService.CheckCard(Customercard));
        }

        public JsonResult GetCost(string Customercard)
        {
            var card = _cardService.GetCardByNumber(Customercard);
            decimal? charges = _packageService.GetPackageCharges(card.Package.Id);
            return Json(charges);
        }

        private CustomerCard GetCard(string c) {
            return _cardService.GetCardByNumber(c);
        }

        private Package GetPackage(int PackageId)
        {
            return _packageService.GetById(PackageId);
        }
    }
}

RDTH/Areas/Admin/Views/Admin/AddAdmin.cshtml
@model RDTH.Areas.Admin.Models.AdminViewModel.AddAdminModel

@{
    ViewData["Title"] = "New Admin";
}

<h2>Add New Admin</h2>

<h4 class="text-warning">Fill the form with correct Information !</h4>
<hr />
<br />

<div class="row">
    <div class="col-md-4">
        <form asp-action="AddAdmin">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RDTH/Areas/Admin/Views/Admin/Index.cshtml
@model RDTH.Areas.Admin.Models.AdminViewModel.AdminIndexViewModel

@{
    ViewData["Title"] = "Dashboard";
}


<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Dashboard <small>Statistics Overview</small>
        </h1>
        <ol class="breadcrumb">
            <li class="active">
                <i class="fa fa-dashboard"></i> Dashboard
            </li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <form asp-controller="CustomerPackage" asp-action="UpdateStatus" method="post">
            <label>Update All Current Packages Recharge Status  |</label>
            <input type="submit" class="btn btn-primary" value="Update" />
        </form>
    </div>
</div>
<br />
<hr />
<div class="row">
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-suitcase fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">@Model.LatestRequest</div>
                        <div>New SetBox Request!</div>
                    </div>
                </div>
            </div>
            <a asp-area="Admin" asp-controller="NewSetboxRequest" asp-action="index">
                <div class="panel-footer">
                    <span class="pull-left">View</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-tasks fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">@Model.LatestSubscribe</div>
                        <div>New Subscription!</div>
                    </div>
                </div>
            </div>
            <a asp-area="Admin" asp-controller="SubscribeAdmin" asp-action="Index">
                <div class="panel-footer">
                    <span class="pull-left">View</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-red">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-shopping-cart fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">@Model.LatestOrders</div>
                        <div>New Orders!</div>
                    </div>
                </div>
            </div>
            <a asp-area="Admin" asp-controller="Order" asp-action="Index">
                <div class="panel-footer">
                    <span class="pull-left">View</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-yellow">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-film fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">@Model.LatestMOD</div>
                        <div>Movies On Demand!</div>
                    </div>
                </div>
            </div>
            <a asp-area="Admin" asp-controller="MOD" asp-action="Index">
                <div class="panel-footer">
                    <span class="pull-left">View</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
</div>

<hr />

<div class="row">
    <div class="col-md-6">
        <h4><span><a asp-area="Admin" asp-controller="FeedBack" asp-action="Index">FeedBacks</a></span></h4>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Message</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var feedback in Model.Feedbacks)
                {
                    <tr>
                        <td>@feedback.Name</td>
                        <td>@feedback.Email</td>
                        <td>@feedback.Msg</td>
                        <td>@feedback.Date</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-md-6">
        <h4><a asp-area="Admin" asp-controller="Recharge" asp-action="Index">Latest Recharge History</a></h4>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Package Name</th>
                    <th>Date</th>
                    <th>Customer Card</th>
                    <th>Customer Name</th>
                    <th>Cost</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var recharge in Model.RechargeCatalog)
                {
                    <tr>
                        <td>@recharge.Package.PackageName</td>
                        <td>@recharge.RechargeDate</td>
                        <td>@recharge.CustomerCard.CardNumber</td>
                        <td>@recharge.CustomerCard.OwnerName</td>
                        <td>@recharge.Cost</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <h4><a asp-area="Admin" asp-controller="Order" asp-action="Index">Latest Orders</a></h4>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Status</th>
                    <th>Person Name</th>
                    <th>Contact</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var order in Model.Orders)
                {
                    <tr>
                        <td>@order.DatePlaced</td>
                        <td>@order.Status.Name</td>
                        <td>@order.PersonName</td>
                        <td>@order.Contact</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-md-6">
        <h4><a asp-area="Admin" asp-controller="Payment" asp-action="Index">Recent Payments</a></h4>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Payment Person</th>
                    <th>Contact</th>
                    <th>Date</th>
                    <th>Payment Type</th>
                    <th>Payment Cost</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var pay in Model.Payments)
                {
                    <tr>
                        <td>@pay.PersonName</td>
                        <td>@pay.Contact</td>
                        <td>@pay.PaymentDate</td>
                        <td>@pay.PaymentType</td>
                        <td>@pay.Cost</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>